# Application Configuration

# Pinecone Configuration
pinecone:
  api_key: "${PINECONE_API_KEY}"
  host_name: "${PINECONE_HOST_NAME}"

# Chunking Parameters
chunking:
  chunk_size: 1000
  overlap: 200

# Queue Backend Configuration
queue:
  backend: "rabbitmq"  # Options: "rabbitmq / sqs"
  rabbitmq:
    connection_string: ${RABBITMQ_CONNECTION}
    queue_name: ${QUEUE_NAME}